OpsPlatform/OpsPlatform/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from userperm import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/',views.dashboard,name='index'),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('api.urls',namespace='api')),
    url(r'^asset/', include('assets.urls',namespace='asset')),
    url(r'^task/', include('task.urls',namespace='task')),
    url(r'^deploy/', include('deploy.urls',namespace='deploy')),

    url(r'', include('userperm.urls')),

    url(r'^login/', views.login_view,name='login'),
    url(r'^logout/', views.logout_view,name='logout'),
    url(r'^register/', views.register_view,name='register'),
    url(r'^noperm$',views.user_noperm,name='user_noperm'),


]

OpsPlatform/api/urls.py
from django.conf.urls import url
from . import views

from rest_framework.urlpatterns import format_suffix_patterns
# router = routers.DefaultRouter()
#
# router.register(r'assets',views.AssetServerViewSet)


# urlpatterns = [
#     url(r'',include(router.urls)),
#     url(r'asset/server',include(router.urls)),
# ]


urlpatterns = [
    url(r'^asset/list/$',views.asset_list),
    url(r'^server/list/$',views.server_list),
    url(r'^user/list/$',views.user_list),
    url(r'^asset/(?P<pk>[0-9]+)/$',views.asset_detail),
    url(r'^server/(?P<pk>[0-9]+)/$',views.server_detail),
    url(r'^user/(?P<pk>[0-9]+)/$',views.user_detail),
]

urlpatterns = format_suffix_patterns(urlpatterns)

OpsPlatform/userperm/urls.py
from django.conf.urls import url
from . import views


app_name = 'userperm'
urlpatterns = [
    url(r'^$',views.dashboard,name='dashboard'),
    url(r'^verify_code$', views.check_code,name='verify_code'),
    url(r'^user_center/$',views.user_list,name='user_list'),
    url(r'^user_add/$',views.user_manage,name='user_add'),
    url(r'^audit/$',views.audit_log,name='audit'),

    url(r'^user_manage/(?P<uid>\d+)/(?P<action>[\w-]+)/$', views.user_manage, name='user_manage'),
    url(r'^group_list$',views.group_list,name='group_list'),
]

OpsPlatform/userperm/models.py
from django.db import models

from userperm import custom_auth
from django.contrib.auth.models import Group,Permission
from django.utils.safestring import mark_safe
# Create your models here.


class Audit(models.Model):
    user = models.CharField(max_length=64)
    audit_time = models.DateTimeField(auto_now_add=True)
    type = models.CharField(max_length=32)
    action = models.CharField(max_length=64)
    action_ip = models.CharField(max_length=32)
    content = models.TextField()

    def __str__(self):
        return self.user

    class Meta:
        permissions = (
            ("can_read_audit","读取审计权限"),
            ("can_change_audit","更改审计权限"),
            ("can_add_audit","添加审计权限"),
            ("can_delete_audit","删除审计权限"),
        )
        ordering = ['-audit_time']

        verbose_name = '审计日志'
        verbose_name_plural = '审计日志'

class User_Profile(custom_auth.AbstractBaseUser,custom_auth.PermissionsMixin):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    password = models.CharField(max_length=128)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(
        verbose_name='staff status',
        default=True,
        help_text='Designates whether the user can log into this admin site.',
    )
    name = models.CharField(max_length=32)
    groups = models.ManyToManyField(Group, help_text=u'员工所属用户组')
    token = models.CharField('token', max_length=128, default=None, blank=True, null=True)
    # roles = models.ManyToManyField('Role', blank=True)
    department = models.CharField('部门', max_length=32, default=None, blank=True, null=True)
    tel = models.CharField('座机', max_length=32, default=None, blank=True, null=True)
    memo = models.TextField('备注', blank=True, null=True, default=None)
    date_joined = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    USERNAME_FIELD = 'email'
    # REQUIRED_FIELDS = ['name','token','department','tel','mobile','memo']
    REQUIRED_FIELDS = ['name']

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):  # __str__ on Python 2
        return self.email

    # def has_perm(self, perm, obj=None):
    #     "Does the user have a specific permission?"
    #     # Simplest possible answer: Yes, always
    #     return True
    def has_perms(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_superuser(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = "用户信息"
    objects = custom_auth.UserManager()

OpsPlatform/userperm/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .form import LoginForm,RegisterForm,UserModelForm
import json
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import logout,login,authenticate
from django.contrib.auth.decorators import login_required
from .models import Audit,User_Profile
from assets.models import Asset
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import permission_required
from io import BytesIO
from utils.verify_code import create_validate_code
from .custom_auth import UserManager

# Create your views here.

def check_code(request):
    stream = BytesIO()
    img,code = create_validate_code()
    img.save(stream,'pNG')
    request.session['verify_code'] = code
    return HttpResponse(stream.getvalue())

def login_ip(request):
    '''获取用户登陆地址'''
    ip_addr = ''
    if request.META.get('HTTP_X_FORWARDED_FOR'):
        ip_addr = request.META['HTTP_X_FORWARDED_FOR']
    else:
        ip_addr = request.META['REMOTE_ADDR']
    return ip_addr

def login_view(request):
    if request.method == 'GET':
        return render(request,'login.html')
    elif request.method == 'POST' and request.is_ajax():
        result = {'status':False,'message':None}
        form = LoginForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user is not None and user.is_active:
                print(form.cleaned_data)
                result['status'] = True
                login(request,user)
                user_info = User_Profile.objects.filter(email=user).values('id', 'email').first()
                request.session['user_info'] = user_info
                Audit.objects.create(type='用户登录',
                                     user=request.user,
                                     action='登录',
                                     action_ip=login_ip(request),
                                     content='用户登录: %s' % request.user)
                if form.cleaned_data.get('rmb'):
                    request.session.set_expiry(60 * 60 * 24 * 7)
            else:
                result['message'] = '用户名或密码错误'

        else:
            if 'verify_code' in form.errors:
                result['message'] = '验证码错误或过期'
            else:
                result['message'] = '用户名或密码错误'
                print(form.errors['password'])
        return HttpResponse(json.dumps(result))

def logout_view(request):
    Audit.objects.create(type='用户退出',
                         user=request.user,
                         action='用户退出',
                         action_ip=login_ip(request),
                         content='用户退出 %s' % request.user)
    logout(request)
    return HttpResponseRedirect("/login/")

def register_view(request):
    if request.method == 'GET':
        return render(request,'register.html')
    elif request.method == 'POST' and request.is_ajax():
        result = {'status':False,'message':None}
        form = RegisterForm(request=request,data=request.POST)
        if form.is_valid() and request.is_ajax():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            username = form.cleaned_data.get('username')
            user_info = User_Profile.objects.filter(email=email).first()
            if not user_info:
                user = User_Profile.objects.create_user(email=email,password=password,name=username)
                # user.is_superuser = True
                user.is_active = True
                user.is_staff = True
                user.save()
                result['status'] = True
                Audit.objects.create(type='用户注册',
                                     user=email,
                                     action='注册',
                                     action_ip=login_ip(request),
                                     content='用户注册成功: %s' % request.user)
            else:
                result['message'] = '用户名已存在'
            return HttpResponse(json.dumps(result))
        else:
            print(form.errors)
            if '__all__' in form.errors:
                result['message'] = '两次密码输入不一致'
            elif 'password' in form.errors:
                result['message'] = '密码不能少于8位'
        return HttpResponse(json.dumps(result))

@login_required
def dashboard(request):
    asset_count = Asset.objects.all().count()
    asset_type = Asset.objects.all()
    physics_count = Asset.objects.filter(asset_type='physics').count()
    server_count = Asset.objects.filter(asset_type='server').count()
    database_count = Asset.objects.filter(asset_type='database').count()
    nosql_count = Asset.objects.filter(asset_type='nosql').count()
    inside_count = Asset.objects.filter(asset_type='inside').count()

    return render(request, 'index.html', {
        'asset_count': asset_count, 'asset_type': asset_type, 'physics_count': physics_count,
        'server_count': server_count, 'database_count': database_count, 'nosql_count': nosql_count,
        'inside_count': inside_count
    })


def user_list(request):
    all_user = User_Profile.objects.all()
    return render(request,'userperm/user-list.html',{'all_user':all_user})

# @permission_required('userperm.change_user',login_url='/noperm/')
def user_manage(request,uid=None,action=None):
    if uid:
        user = get_object_or_404(User_Profile, pk=uid)
        if action == 'edit':
            page_name = '编辑用户'
        if action == 'delete':
            user.delete()
            Audit.objects.create(type='用户管理',
                                   user=request.user.first_name,
                                   action='删除用户',
                                   action_ip=login_ip(request),
                                   content='删除用户 %s%s，用户名 %s' % (user.last_name, user.first_name, user.username))
            return redirect('user_list')
    else:
        user = User_Profile()
        action = 'add'
        page_name = '新增用户'

    if request.method == 'POST':
        print(request.POST)
        form = UserModelForm(request.POST,instance=user)
        print('===>%s' % form)
        if form.is_valid():
            password1 = request.POST.get('password1')
            password2 = request.POST.get('password2')
            group_select = request.POST.getlist('group_sel')
            group_delete = request.POST.getlist('group_del')
            perm_select = request.POST.getlist('perm_sel')
            perm_delete = request.POST.getlist('perm_del')
            if action == 'add' or action == 'edit':
                form.save()
                if password1 and password1 == password2:
                    user.set_password(password1)
                user.save()
                user.group.add(*group_select)
                user.group.remove(*group_delete)
                user.user_permissions.add(*perm_select)
                user.user_permissions.remove(*perm_delete)
                Audit.objects.create(type='用户管理',
                                       user=request.user.first_name,
                                       action='编辑',
                                       action_ip=login_ip(request),
                                       content='%s %s%s，用户名 %s' % (
                                           '编辑', user.last_name, user.first_name, user.username))
                return redirect('user_list')
    else:
        form = UserModelForm(instance=user)
    return render(request,'userperm/user-manage.html',{'form': form,  'action': action, 'uid': uid})

def user_noperm(request):
    return render(request,'userperm/forbidden.html')

def audit_log(request):
    logs = Audit.objects.all()[:300]
    if request.method == 'GET':
        if request.GET.get('uid'):
            aid = request.get_full_path().split('=')[1]
            log_detail = Audit.objects.filter(id=aid)
            return render(request, 'userperm/audit-detail.html',
                          {'log_detail': log_detail})

    return render(request, 'userperm/audit.html', {'logs': logs})



def group_list(request):
    obj = Group.objects.all()
    return render(request,'userperm/group-list.html',{'obj':obj})

OpsPlatform/templates/userperm/audit.html
{% extends 'base.html' %}

{% block css %}
    <!-- Data Tables -->
    <link href="/static/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
{% endblock css %}


{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><strong>用户操作</strong></h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项1</a>
                                </li>
                                <li><a href="#">选项2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <table id="datatable" class="table table-striped table-bordered table-hover dataTables-example">
                            <thead>
                            <tr>
                                <th>详细</th>
                                    <th>用户</th>
                                    <th>用户IP</th>
                                    <th>操作时间</th>
                                    <th>类别</th>
                                    <th>操作</th>
                                    <th>详细信息</th>
                            </tr>
                            </thead>
                            <tbody>
                           {% for i in logs %}
                                <tr>
                                    <td>
{#                                        <a href="{% url 'log_audit' %}?uid={{ i.pk }}"><i class="fa fa-envelope "></i></a>#}
                                        <a href="#"><i class="fa fa-envelope "></i></a>
                                    </td>
                                    <td>{{ i.user }}</td>
                                    <td>{{ i.action_ip }}</td>
                                    <td>{{ i.audit_time|date:"Y-m-d H:i:s" }}</td>
                                    <td>{{ i.type }}</td>
                                    <td>{{ i.action }}</td>
                                    <td>{{ i.content|safe|truncatewords:"10" }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>


                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <!-- Data Tables -->
    <script src="/static/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="/static/js/plugins/dataTables/dataTables.bootstrap.js"></script>


    <script>
        $(document).ready(function () {
            $('#datatable').dataTable();
        });

    </script>


{% endblock js %}

OpsPlatform/templates/userperm/forbidden.html
{% extends 'base.html' %}

{% block css %}

{% endblock css %}

{% block content %}
    <div class="middle-box text-center animated fadeInDown">
        <h1>403</h1>
        <h3 class="font-bold">Forbidden！</h3>

        <div class="error-desc">
            <h3 style="color: #3c763d">抱歉，没有权限操作</h3>
            <form class="form-inline m-t" role="form">
                <div class="form-group">
                    <input type="email" class="form-control" placeholder="请输入您需要查找的内容 …">
                </div>
                <button type="submit" class="btn btn-primary">搜索</button>
            </form>
        </div>
    </div>
{% endblock content %}

OpsPlatform/templates/userperm/group-list.html
{% extends 'base.html' %}

{% block content %}

    {% for g in obj %}
        {{ g.name }}
    {% endfor %}

{% endblock content %}

OpsPlatform/templates/userperm/tag_permissions.html
<div class="col-xs-5">
    <div class="x_title"><h4>所有权限</h4></div>
    <select id="search" class="form-control" size="8" multiple="multiple">
        {% for k,v in permissions_dict.items %}
            <option name="permission" value="{{ k }}">{{ v }}</option>
        {% endfor %}
    </select>
</div>

<div class="col-xs-2" style="padding-top:60px;">
    <button type="button" id="search_rightAll" class="btn btn-block"><i class="fa fa-forward"></i></button>
    <button type="button" id="search_rightSelected" class="btn btn-block"><i class="fa fa-chevron-right"></i></button>
    <button type="button" id="search_leftSelected" class="btn btn-block"><i class="fa fa-chevron-left"></i></button>
    <button type="button" id="search_leftAll" class="btn btn-block"><i class="fa fa-backward"></i></button>
</div>

<div class="col-xs-5">
    <div><h4>已选权限</h4></div>
    <select id="search_to" class="form-control" size="8" multiple="multiple">
        {% if select_permissions_dict %}
            {% for k,v in select_permissions_dict.items %}
                <option name="permission_select" value="{{ k }}">{{ v }}</option>
            {% endfor %}
        {% endif %}
    </select>
</div>

OpsPlatform/templates/userperm/user-list.html
{% extends 'base.html' %}

{% block css %}
    <!-- Data Tables -->
    <link href="/static/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
    <!-- Sweet Alert -->
    <link href="/static/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">
{% endblock css %}


{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><strong>用户中心</strong></h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项1</a>
                                </li>
                                <li><a href="#">选项2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <table id="datatable" class="table table-striped table-bordered table-hover dataTables-example">
                            <thead>
                            <tr>
                                <th>名字</th>
                                <th>邮箱</th>
                                <th>状态</th>
                                <th>管理员</th>
                                <th>所属组</th>
                                <th>操作</th>
                                <th>最近登录时间</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for u in all_user %}
                                <tr class="gradeA">
                                    <td>{{ u.name }}</td>
                                    <td>{{ u.email }}</td>
                                    <td>{% if u.is_active %}
                                        <span class="btn btn-success btn-sm">激活</span>{% else %}
                                        <span class="btn btn-default btn-sm">冻结</span>{% endif %}</td>
                                    <td>{% if u.is_admin %}
                                        <span class="btn btn-success btn-sm">是</span>{% else %}
                                        <span class="btn btn-default btn-sm">否</span>{% endif %}</td>
                                    <td>{{ u.groups }}</td>
                                    <td class="center"><a href="{% url 'userperm:user_manage' uid=u.pk action='edit' %}"
                                                          class="btn btn-warning btn-sm" role="button"><i
                                            class="fa fa-pencil"></i></a>
                                        <button href="#" id="del" value="{{ u.pk }}" class="btn btn-danger btn-sm demo4"><i
                                                class="fa fa-trash-o "></i></button>
{#                                        <a href="{% url 'user_manage' uid=id action='delete' %}" class="hide">123</a>#}

                                    </td>
                                    <td class="center">{{ u.last_login|date:"Y-m-d H:i:s" }}</td>
                                </tr>

                            {% endfor %}
                            </tbody>
                        </table>


                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <!-- Data Tables -->
    <script src="/static/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="/static/js/plugins/dataTables/dataTables.bootstrap.js"></script>

    <!-- Sweet alert -->
    <script src="/static/js/plugins/sweetalert/sweetalert.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#datatable').dataTable();

            $('.demo4').click(function () {
                id = $(this).attr("value");
                swal({
                        title: "您确定要删除这条记录",
                        text: "删除后将无法恢复，请谨慎操作！",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "是的，我要删除！",
                        cancelButtonText: "让我再考虑一下…",
                        closeOnConfirm: false,
                        closeOnCancel: false
                    },
                    function (isConfirm) {
                        if (isConfirm) {
                            base_url = /user_manage/ + id + '/' + 'delete' ;
                            location.href = base_url;
                            location.href = "{% url 'userperm:user_list' %}";
                            swal("删除成功！", "您已经永久删除了这条信息。", "success");
                        } else {
                            swal("已取消", "您取消了删除操作！", "error");
                        }
                    });


            });
        });

    </script>


{% endblock js %}