OpsPlatform/OpsPlatform/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from userperm import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/',views.dashboard,name='index'),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('api.urls',namespace='api')),
    url(r'^asset/', include('assets.urls',namespace='asset')),
    url(r'^task/', include('task.urls',namespace='task')),
    url(r'^deploy/', include('deploy.urls',namespace='deploy')),

    url(r'', include('userperm.urls')),

    url(r'^login/', views.login_view,name='login'),
    url(r'^logout/', views.logout_view,name='logout'),
    url(r'^register/', views.register_view,name='register'),
    url(r'^noperm$',views.user_noperm,name='user_noperm'),


]

OpsPlatform/api/urls.py
from django.conf.urls import url
from . import views

from rest_framework.urlpatterns import format_suffix_patterns
# router = routers.DefaultRouter()
#
# router.register(r'assets',views.AssetServerViewSet)


# urlpatterns = [
#     url(r'',include(router.urls)),
#     url(r'asset/server',include(router.urls)),
# ]


urlpatterns = [
    url(r'^asset/list/$',views.asset_list),
    url(r'^server/list/$',views.server_list),
    url(r'^user/list/$',views.user_list),
    url(r'^asset/(?P<pk>[0-9]+)/$',views.asset_detail),
    url(r'^server/(?P<pk>[0-9]+)/$',views.server_detail),
    url(r'^user/(?P<pk>[0-9]+)/$',views.user_detail),
]

urlpatterns = format_suffix_patterns(urlpatterns)

OpsPlatform/assets/urls.py
from django.conf.urls import url

from . import views



urlpatterns = [
    url(r'^list/$',views.asset_list,name='asset_list'),
    url(r'^add/$',views.asset_add,name='asset_add'),
    url(r'^server/add/$',views.server_add,name='server_add'),
    url(r'^chart/$',views.test_chart,name='chart'),
    url(r'^manage/(?P<nid>\d+)/(?P<action>[\w-]+)$',views.asset_manage,name='asset_manage'),
]

OpsPlatform/deploy/urls.py
from django.conf.urls import url

from . import views



urlpatterns = [
    url(r'^index/$',views.index,name='index'),
    url(r'^upload/$',views.upload,name='upload'),
    # url(r'^upload/success$',views.upload_success,name='success'),
]

OpsPlatform/userperm/urls.py
from django.conf.urls import url
from . import views


app_name = 'userperm'
urlpatterns = [
    url(r'^$',views.dashboard,name='dashboard'),
    url(r'^verify_code$', views.check_code,name='verify_code'),
    url(r'^user_center/$',views.user_list,name='user_list'),
    url(r'^user_add/$',views.user_manage,name='user_add'),
    url(r'^audit/$',views.audit_log,name='audit'),

    url(r'^user_manage/(?P<uid>\d+)/(?P<action>[\w-]+)/$', views.user_manage, name='user_manage'),
    url(r'^group_list$',views.group_list,name='group_list'),
]

OpsPlatform/assets/models.py
from django.db import models

# Create your models here.

class Asset(models.Model):
    asset_type_choice = (
        ('physics','物理服务器'),
        ('server','云主机'),
        ('database','云数据库实例'),
        ('nosql','非关系型数据库实例'),
        ('inside','内网服务器'),
    )
    status_choices = ((0, '在线'),
                      (1, '已下线'),
                      (2, '未知'),
                      (3, '故障'),
                      (4, '备用'),
                      )
    asset_type = models.CharField(choices=asset_type_choice,max_length=100,default='server',verbose_name='资产类型')
    name = models.CharField(max_length=100,unique=True,verbose_name='资产编号')
    loaction = models.ForeignKey('Location',related_name='location_name',verbose_name='位置')
    management_ip = models.GenericIPAddressField(blank=True,null=True,verbose_name='管理IP')
    project = models.ForeignKey('Project',related_name='project_name',verbose_name='所属项目')
    provider = models.ForeignKey('Provider',related_name='provider_name',verbose_name='服务商')
    status = models.SmallIntegerField(choices=status_choices, default=0,verbose_name='状态')
    server_info = models.OneToOneField('Asset_Server',on_delete=models.CASCADE,verbose_name='关联信息')

    class Meta:
        permissions = (
            ("can_read_asset","读取资产"),
            ("can_change_asset","编辑资产"),
            ("can_add_asset","添加资产"),
            ("can_delete_asset","删除资产"),
        )
        ordering = ['-management_ip']
        verbose_name = '资产表'
        verbose_name_plural = "资产表"

    def __str__(self):
        return '<id:%s name:%s>' % (self.id, self.name)

class Asset_Server(models.Model):
    system_type_choices = (
        ('win','Windows'),
        ('lin','Centos'),
    )
    system_version_choices = (
        ('win08', 'Windows Server 2008'),
        ('win12', 'Windows Server 2012'),
        ('lin06', 'Centos 6'),
        ('lin07', 'Centos 7'),
    )
    ip_addr = models.GenericIPAddressField(unique=True,verbose_name='IP地址')
    hostname = models.CharField(max_length=100,verbose_name='主机名')
    username = models.CharField(max_length=100,blank=True,null=True,verbose_name='用户名')
    password = models.CharField(max_length=100,blank=True,null=True,verbose_name='密码')
    port = models.IntegerField(blank=True,null=True,verbose_name='远程端口')
    system_type = models.CharField(max_length=64, choices=system_type_choices, default='win', verbose_name='操作系统')
    system_version = models.CharField(max_length=64,choices=system_version_choices,default='win08',verbose_name='系统版本')
    cpu = models.SmallIntegerField(blank=True,null=True,verbose_name='CPU')
    disk = models.CharField(max_length=32,verbose_name='硬盘')
    memory = models.CharField(max_length=32, verbose_name='内存')

    class Meta:
        permissions = (
            ("can_read_server","读取服务器权限"),
            ("can_change_server","更改服务器权限"),
            ("can_add_server","添加服务器权限"),
            ("can_delete_server","删除服务器权限"),
        )
        verbose_name = "服务器表"
        verbose_name_plural = "服务器表"

    def __str__(self):
        return '%s' % self.ip_addr

class Project(models.Model):
    name = models.CharField(max_length=100,unique=True)
    class Meta:
        permissions = (
            ("can_read_project", "读取项目权限"),
            ("can_change_project", "更改服务器权限"),
            ("can_add_project", "添加服务器权限"),
            ("can_delete_project", "删除服务器权限"),
        )
        verbose_name = "项目表"
        verbose_name_plural = "项目表"
    def __str__(self):
        return self.name

class Location(models.Model):
    name = models.CharField(max_length=64,unique=True)

    class Meta:
        permissions = (
            ("can_read_location", "读取机房权限"),
            ("can_change_location", "更改机房权限"),
            ("can_add_location", "添加机房权限"),
            ("can_delete_location", "删除机房权限"),
        )
        verbose_name = '机房表'
        verbose_name_plural = "机房表"

    def __str__(self):
        return self.name

class Provider(models.Model):
    name = models.CharField(max_length=64,unique=True)
    deadline = models.TextField(unique=True)

    class Meta:
        permissions = (
            ("can_read_provider", "读取服务商权限"),
            ("can_change_provider", "更改服务商权限"),
            ("can_add_provider", "添加服务商权限"),
            ("can_delete_provider", "删除服务商权限"),
        )
        verbose_name = '服务商表'
        verbose_name_plural = "服务商表"

    def __str__(self):
        return self.name

OpsPlatform/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">

    <title> CoolFish运维 </title>

    <meta name="keywords" content="">
    <meta name="description" content="">


    <link rel="shortcut icon" href="/static/favicon-20180201055603578.ico">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/font-awesome.min.css?v=4.4.0" rel="stylesheet">
    <link href="/static/css/animate.css" rel="stylesheet">
    <link href="/static/css/style.css?v=4.1.0" rel="stylesheet">
    {% block css %}

    {% endblock css %}

</head>

<body class="fixed-sidebar full-height-layout gray-bg" style="overflow:hidden">
    <div id="wrapper">
        <!--左侧导航开始-->
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="nav-close"><i class="fa fa-times-circle"></i>
            </div>
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear">
                                    <span class="block m-t-xs" style="font-size:20px;">
                                        <i class="fa fa-area-chart"></i>
                                        <strong class="font-bold">CoolFish</strong>
                                    </span>
                                </span>
                            </a>
                        </div>
                        <div class="logo-element">Admin
                        </div>
                    </li>
                    <li class="hidden-folded padder m-t m-b-sm text-muted text-xs">
                        <span class="ng-scope">分类</span>
                    </li>
                    <li>
                        <a class="J_menuItem" href="{% url 'userperm:dashboard' %}">
                            <i class="fa fa-home"></i>
                            <span class="nav-label">主页</span>
                        </a>
                    </li>


                    <li class="hidden-folded padder m-t m-b-sm text-muted text-xs">
                        <span class="ng-scope">分类</span>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa fa-table"></i>
                            <span class="nav-label">资产管理</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="{% url 'asset:asset_list' %}">资产列表</a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="{% url 'asset:asset_add' %}">资产添加</a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="{% url 'asset:server_add' %}">服务器添加</a>
                            </li>
                            <li>

                                <a class="J_menuItem" href="{% url 'asset:chart' %}">服务器分布</a>
                            </li>
                        </ul>
                    </li>
                    <li class="line dk"></li>
                    <li class="hidden-folded padder m-t m-b-sm text-muted text-xs">
                        <span class="ng-scope">分类</span>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-cubes"></i> <span class="nav-label">任务管理</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a class="J_menuItem" href="{% url 'task:cron-list' %}">Cron列表</a>
                            </li>
                            <li><a class="J_menuItem" href="{% url 'task:cron-add' %}">Cron添加</a>
                            </li>
                            <li><a class="J_menuItem" href="#">任务导入</a>
                            </li>

                        </ul>
                    </li>

                    <li class="line dk"></li>
                    <li class="hidden-folded padder m-t m-b-sm text-muted text-xs">
                        <span class="ng-scope">分类</span>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-desktop"></i> <span class="nav-label">应用部署</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a class="J_menuItem" href="{% url 'task:salt-list' %}">Salt列表</a>
                            </li>
                            <li><a class="J_menuItem" href="#">Salt状态</a>
                            </li>
                            <li><a class="J_menuItem" href="{% url 'task:salt-group' %}">Salt分组</a>
                            </li>
                            <li><a class="J_menuItem" href="{% url 'task:salt-exec' %}">Salt命令</a>
                            </li>

                        </ul>
                    </li>

                    <li class="line dk"></li>
                    <li class="hidden-folded padder m-t m-b-sm text-muted text-xs">
                        <span class="ng-scope">分类</span>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-desktop"></i> <span class="nav-label">更新维护</span><span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><a class="J_menuItem" href="{% url 'deploy:index' %}">更新操作</a>
                            </li>
                            <li><a class="J_menuItem" href="#">asdas</a>
                            </li>
                            <li><a class="J_menuItem" href="{% url 'deploy:upload' %}">文件上传</a>
                            </li>
                            <li><a class="J_menuItem" href="#">更新日志</a>
                            </li>

                        </ul>
                    </li>

                    <li class="line dk"></li>
                    <li class="hidden-folded padder m-t m-b-sm text-muted text-xs">
                        <span class="ng-scope">分类</span>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa fa-user"></i>
                            <span class="nav-label">用户中心</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a class="J_menuItem" href="{% url 'userperm:user_list' %}">用户列表</a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="{% url 'userperm:audit' %}">审计操作</a>
                            </li>
                            <li>
                                <a class="J_menuItem" href="{% url 'logout' %}">退出</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
        <!--左侧导航结束-->
        <!--右侧部分开始-->
        <div id="page-wrapper" class="gray-bg ">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header"><a class="navbar-minimalize minimalize-styl-2 btn btn-info " href="#"><i class="fa fa-bars"></i> </a>

                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li class="dropdown">
                            <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">

                                <i class="fa fa-user"></i> <span style="color: #00B2E2">{{ request.user}}</span>
                            </a>
                            <ul class="dropdown-menu dropdown-alerts">
                             <li>
                                    <a href="#">
                                            <i class="pull-right fa fa-envelope fa-fw"></i>切换到Admin管理后台
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="{% url 'logout' %}">
                                            <i class=" pull-right  fa fa-qq fa-fw"></i>退出当前用户
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>


                {% block content %}

                {% endblock content %}
            </div>
        </div>
        <!--右侧部分结束-->
    </div>

    <!-- 全局js -->
    <script src="/static/js/jquery.min.js?v=2.1.4"></script>
    <script src="/static/js/bootstrap.min.js?v=3.3.6"></script>

    {% block js %}

{% endblock js %}

    <script src="/static/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="/static/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="/static/js/plugins/layer/layer.min.js"></script>

    <!-- 自定义js -->
    <script src="/static/js/hAdmin.js?v=4.1.0"></script>
{#    <script type="text/javascript" src="/static/js/index.js"></script>#}

    <!-- 第三方插件 -->
    <script src="/static/js/plugins/pace/pace.min.js"></script>




</body>

</html>

OpsPlatform/templates/index.html
{% extends 'base.html' %}

{% block css %}
    <link href="/static/css/custom.css" rel="stylesheet">
{% endblock css %}

{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5><strong>图表中心</strong></h5>
                </div>

                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-warning">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-tasks  fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">{{ asset_count }}</div>
                                        <div>总资产</div>
                                    </div>
                                </div>
                            </div>
                            <a href="{% url 'asset:asset_list' %}">
                                <div class="panel-footer">
                                    <span class="pull-left">查看所有</span> <span class="pull-right"><i
                                        class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-database fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">10</div>
                                        <div>设备资产</div>
                                    </div>
                                </div>
                            </div>
                            <a href="#">
                                <div class="panel-footer">
                                    <span class="pull-left">查看所有</span> <span class="pull-right"><i
                                        class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-github-alt fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">0</div>
                                        <div>部署项目</div>
                                    </div>
                                </div>
                            </div>
                            <a href=#>
                                <div class="panel-footer">
                                    <span class="pull-left">查看所有</span> <span class="pull-right"><i
                                        class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-danger">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-clock-o fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">5</div>
                                        <div>计划任务</div>
                                    </div>
                                </div>
                            </div>
                            <a href="#">
                                <div class="panel-footer">
                                    <span class="pull-left">查看所有</span> <span class="pull-right"><i
                                        class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="hr-line-dashed"></div>

                <div class="row">
                    <div class="col-lg-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <i class="fa fa-bar-chart-o fa-fw"></i> 用户代码部署统计
                                <div class="pull-right">
                                    <div class="btn-group">

                                    </div>
                                </div>
                            </div>
                            <!-- /.panel-heading -->
                            <div class="panel-body">
                                <div id="morris-area-chart" style="width: 100%; height: 400px"></div>
                            </div>
                            <!-- /.panel-body -->
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <i class="fa fa-bar-chart-o fa-fw"></i> 服务器统计
                                <div class="pull-right">
                                    <div class="btn-group">

                                    </div>
                                </div>
                            </div>
                            <!-- /.panel-heading -->
                            <div class="panel-body">
                                <div id="main" style="width: 100%; height: 400px"></div>
                            </div>
                            <!-- /.panel-body -->
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script src="/static/js/echarts.min.js"></script>

    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));

        // 指定图表的配置项和数据
        var option = {
            title: {
                text: '服务器分类'
            },
            tooltip: {},
            legend: {
                data: ['类型']
            },
            xAxis: {
                data: ["物理机", "云主机", "NOSQL", "云数据库", "内网服务器"]
                {#                data: [#}
                {#                    {% for type in asset_type %}#}
                {#                        '{{ type.get_asset_type_display }}',#}
                {#                    {% endfor %}#}
                {#                ]#}
            },
            yAxis: {},
            series: [{
                name: '台数',
                type: 'bar',
                {#                data: [5, 20, 36, 10, 10]#}
                data: [
                    {{ physics_count }},
                    {{ server_count }},
                    {{ database_count }},
                    {{ nosql_count }},
                    {{ inside_count }}
                ]
            }]
        };

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);

        var myChart = echarts.init(document.getElementById("morris-area-chart"));
        var option = {
            title: {
                text: '最近7天部署',
                subtext: '更新统计'
            },
            tooltip: {
                trigger: 'axis'
            },
            legend: {
                data: ['次数']
            },
            toolbox: {
                show: true,
                feature: {
                    mark: {show: true},
                    dataView: {show: true, readOnly: false},
                    magicType: {show: true, type: ['line', 'bar']},
                    restore: {show: true},
                    saveAsImage: {show: true}
                }
            },
            calculable: true,
            xAxis: [
                {
                    type: 'category',
                    boundaryGap: false,
                    data: ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
                }
            ],
            yAxis: [
                {
                    type: 'value',
                }
            ],
            series: [
                {
                    name: '次数',
                    type: 'line',
                    data: [3, 1, 5, 2, 0, 0, 1],
                    markPoint: {
                        data: [
                            {type: 'max', name: '最大值'},
                            {type: 'min', name: '最小值'}
                        ]
                    },
                    markLine: {
                        data: [
                            {type: 'average', name: '平均值'}
                        ]
                    }
                },
            ]
        };


        // 为echarts对象加载数据
        myChart.setOption(option);


    </script>


{% endblock js %}

OpsPlatform/templates/login.html
<!DOCTYPE html>
<html>

<head lang="en">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <title> - 登录</title>
    <meta name="keywords" content="">
    <meta name="description" content="">

    <link rel="shortcut icon" href="/static/favicon.ico">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/font-awesome.css" rel="stylesheet">
    <link href="/static/css/plugins/iCheck/custom.css" rel="stylesheet">
    <link href="/static/css/animate.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">

</head>

<body class="gray-bg">

<div class="middle-box text-center loginscreen  animated fadeInDown">
    <div>
        <div>

            <h1 class="logo-name">C</h1>

        </div>
        <h3>欢迎使用 CoolFish运维系统</h3>

        <form id="fm" class="m-t" role="form" method="post" action="{% url 'login' %}">{% csrf_token %}
            <div class="form-group">
                <input type="email" class="form-control" name="username" placeholder="邮箱" required="">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="password" placeholder="密码" required="">
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col-xs-7">
                        <input type="text" class="form-control" name="verify_code" placeholder="验证码" required="">
                    </div>
                    <div class="col-xs-4">
                        <img id="verify_code_img" src="{% url 'userperm:verify_code' %}" onclick="changeImg(this)">
                    </div>
                </div>
            </div>

            <div class="form-group text-left">
                    <div class="checkbox i-checks">
                        <label class="no-padding">
                            <input type="checkbox" value="1" name="rmb"><i></i> 一个月内自动登陆</label>
                    </div>
            </div>

            <a id="submit" type="submit" class="btn btn-primary block full-width m-b">登 录</a>
            <div class="" style="padding-left: 0;">
                <div class="alert-err  alert-danger hide" >
                    <span style="padding: 0 5px 0 5px;display: inline-block;font-size: 14px">
                        <i class="fa fa-minus-circle" aria-hidden="true"></i>
                    </span>
                    <span id="error_msg" style="font-size: 12px;"></span>
                </div>
            </div>


            <p class="text-muted text-center"><a href="login.html#">
                <small>忘记密码？</small>
            </a> | <a href="register.html">注册新账号</a>

            </p>
        </form>
    </div>
</div>

<!-- 全局js -->
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="/static/js/plugins/iCheck/icheck.min.js"></script>

<script type="text/javascript">
        $(function () {
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
            bindLogin();
        });
        function changeImg(ths) {
        ths.src = ths.src + "?"
    }

        function bindLogin() {
            $('#submit').click(function () {
                var $msg = $('#error_msg');
                $msg.parent().addClass('hide');
                $.ajax({
                    url: "{% url 'login' %}",
                    type: 'POST',
                    data: $('#fm').serialize(),
                    //预期服务器返回的数据类型
                    dataType: 'JSON',
                    success: function (callback) {
                        console.log(callback)
                        if (callback.status){
                            location.href = '{% url 'index' %} '
                        }else{
                            //失败显示错误信息
                            $msg.parent().removeClass('hide');
                            $msg.text(callback.message);
                            var img = $('#verify_code_img')[0];
                            console.log(img)
                            //刷新图片验证码
                            img.src = img.src + '?';
                            //清空表单中的信息
                            $('#password,#verify_code').val('');
                        }
                    }
                })

            })
        }

    </script>

</body>

</html>