OpsPlatform/OpsPlatform/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from userperm import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/',views.dashboard,name='index'),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('api.urls',namespace='api')),
    url(r'^asset/', include('assets.urls',namespace='asset')),
    url(r'^task/', include('task.urls',namespace='task')),
    url(r'^deploy/', include('deploy.urls',namespace='deploy')),

    url(r'', include('userperm.urls')),

    url(r'^login/', views.login_view,name='login'),
    url(r'^logout/', views.logout_view,name='logout'),
    url(r'^register/', views.register_view,name='register'),
    url(r'^noperm$',views.user_noperm,name='user_noperm'),


]

OpsPlatform/api/urls.py
from django.conf.urls import url
from . import views

from rest_framework.urlpatterns import format_suffix_patterns
# router = routers.DefaultRouter()
#
# router.register(r'assets',views.AssetServerViewSet)


# urlpatterns = [
#     url(r'',include(router.urls)),
#     url(r'asset/server',include(router.urls)),
# ]


urlpatterns = [
    url(r'^asset/list/$',views.asset_list),
    url(r'^server/list/$',views.server_list),
    url(r'^user/list/$',views.user_list),
    url(r'^asset/(?P<pk>[0-9]+)/$',views.asset_detail),
    url(r'^server/(?P<pk>[0-9]+)/$',views.server_detail),
    url(r'^user/(?P<pk>[0-9]+)/$',views.user_detail),
]

urlpatterns = format_suffix_patterns(urlpatterns)

OpsPlatform/assets/urls.py
from django.conf.urls import url

from . import views



urlpatterns = [
    url(r'^list/$',views.asset_list,name='asset_list'),
    url(r'^add/$',views.asset_add,name='asset_add'),
    url(r'^server/add/$',views.server_add,name='server_add'),
    url(r'^chart/$',views.test_chart,name='chart'),
    url(r'^manage/(?P<nid>\d+)/(?P<action>[\w-]+)$',views.asset_manage,name='asset_manage'),
]

OpsPlatform/assets/models.py
from django.db import models

# Create your models here.

class Asset(models.Model):
    asset_type_choice = (
        ('physics','物理服务器'),
        ('server','云主机'),
        ('database','云数据库实例'),
        ('nosql','非关系型数据库实例'),
        ('inside','内网服务器'),
    )
    status_choices = ((0, '在线'),
                      (1, '已下线'),
                      (2, '未知'),
                      (3, '故障'),
                      (4, '备用'),
                      )
    asset_type = models.CharField(choices=asset_type_choice,max_length=100,default='server',verbose_name='资产类型')
    name = models.CharField(max_length=100,unique=True,verbose_name='资产编号')
    loaction = models.ForeignKey('Location',related_name='location_name',verbose_name='位置')
    management_ip = models.GenericIPAddressField(blank=True,null=True,verbose_name='管理IP')
    project = models.ForeignKey('Project',related_name='project_name',verbose_name='所属项目')
    provider = models.ForeignKey('Provider',related_name='provider_name',verbose_name='服务商')
    status = models.SmallIntegerField(choices=status_choices, default=0,verbose_name='状态')
    server_info = models.OneToOneField('Asset_Server',on_delete=models.CASCADE,verbose_name='关联信息')

    class Meta:
        permissions = (
            ("can_read_asset","读取资产"),
            ("can_change_asset","编辑资产"),
            ("can_add_asset","添加资产"),
            ("can_delete_asset","删除资产"),
        )
        ordering = ['-management_ip']
        verbose_name = '资产表'
        verbose_name_plural = "资产表"

    def __str__(self):
        return '<id:%s name:%s>' % (self.id, self.name)

class Asset_Server(models.Model):
    system_type_choices = (
        ('win','Windows'),
        ('lin','Centos'),
    )
    system_version_choices = (
        ('win08', 'Windows Server 2008'),
        ('win12', 'Windows Server 2012'),
        ('lin06', 'Centos 6'),
        ('lin07', 'Centos 7'),
    )
    ip_addr = models.GenericIPAddressField(unique=True,verbose_name='IP地址')
    hostname = models.CharField(max_length=100,verbose_name='主机名')
    username = models.CharField(max_length=100,blank=True,null=True,verbose_name='用户名')
    password = models.CharField(max_length=100,blank=True,null=True,verbose_name='密码')
    port = models.IntegerField(blank=True,null=True,verbose_name='远程端口')
    system_type = models.CharField(max_length=64, choices=system_type_choices, default='win', verbose_name='操作系统')
    system_version = models.CharField(max_length=64,choices=system_version_choices,default='win08',verbose_name='系统版本')
    cpu = models.SmallIntegerField(blank=True,null=True,verbose_name='CPU')
    disk = models.CharField(max_length=32,verbose_name='硬盘')
    memory = models.CharField(max_length=32, verbose_name='内存')

    class Meta:
        permissions = (
            ("can_read_server","读取服务器权限"),
            ("can_change_server","更改服务器权限"),
            ("can_add_server","添加服务器权限"),
            ("can_delete_server","删除服务器权限"),
        )
        verbose_name = "服务器表"
        verbose_name_plural = "服务器表"

    def __str__(self):
        return '%s' % self.ip_addr

class Project(models.Model):
    name = models.CharField(max_length=100,unique=True)
    class Meta:
        permissions = (
            ("can_read_project", "读取项目权限"),
            ("can_change_project", "更改服务器权限"),
            ("can_add_project", "添加服务器权限"),
            ("can_delete_project", "删除服务器权限"),
        )
        verbose_name = "项目表"
        verbose_name_plural = "项目表"
    def __str__(self):
        return self.name

class Location(models.Model):
    name = models.CharField(max_length=64,unique=True)

    class Meta:
        permissions = (
            ("can_read_location", "读取机房权限"),
            ("can_change_location", "更改机房权限"),
            ("can_add_location", "添加机房权限"),
            ("can_delete_location", "删除机房权限"),
        )
        verbose_name = '机房表'
        verbose_name_plural = "机房表"

    def __str__(self):
        return self.name

class Provider(models.Model):
    name = models.CharField(max_length=64,unique=True)
    deadline = models.TextField(unique=True)

    class Meta:
        permissions = (
            ("can_read_provider", "读取服务商权限"),
            ("can_change_provider", "更改服务商权限"),
            ("can_add_provider", "添加服务商权限"),
            ("can_delete_provider", "删除服务商权限"),
        )
        verbose_name = '服务商表'
        verbose_name_plural = "服务商表"

    def __str__(self):
        return self.name

OpsPlatform/assets/forms.py
# -*- coding:utf-8 -*-  

from .models import Asset,Asset_Server
from django import forms

class AssetModeForm(forms.ModelForm):
    class Meta:
        model = Asset
        # exclude = ['server_info']
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}, ),
            'loaction': forms.Select(attrs={'class': 'form-control'}),
            'management_ip': forms.TextInput(attrs={'class': 'form-control'}),
            'project': forms.Select(attrs={'class': 'form-control'}),
            'provider': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'asset_type': forms.Select(attrs={'class': 'form-control'}),
            'server_info': forms.Select(attrs={'class': 'form-control'}),
        }

class ServerModeForm(forms.ModelForm):
    class Meta:
        model = Asset_Server
        fields = '__all__'
        widgets = {
            'ip_addr': forms.TextInput(attrs={'class': 'form-control'}, ),
            'hostname': forms.TextInput(attrs={'class': 'form-control'}, ),
            'username': forms.TextInput(attrs={'class': 'form-control'}, ),
            'password': forms.TextInput(attrs={'class': 'form-control'}, ),
            'port': forms.NumberInput(attrs={'class': 'form-control'}, ),
            'system_type': forms.Select(attrs={'class': 'form-control'}),
            'system_version': forms.Select(attrs={'class': 'form-control'}),
            'cpu': forms.NumberInput(attrs={'class': 'form-control'}, ),
            'disk': forms.NumberInput(attrs={'class': 'form-control'}, ),
            'memory': forms.NumberInput(attrs={'class': 'form-control'}, ),
        }

OpsPlatform/assets/views.py
from django.shortcuts import render,HttpResponse,get_object_or_404,HttpResponseRedirect
from .models import Asset,Asset_Server
from .forms import AssetModeForm,ServerModeForm
import xlwt
from io import StringIO
from utils.excel import SheetWrite
# Create your views here.

def asset_list(request):
    ass_list = Asset.objects.all()
    if request.GET.get('nid'):
        nid = request.get_full_path().split('=')
        server_detail = Asset.objects.filter(pk=nid).first()
        return render(request, 'asset/asset-detail.html', {'server_detail': server_detail})
    if request.GET.get('export'):
        pass
    return render(request, 'asset/asset-list.html', {'ass_list':ass_list})

def asset_manage(request,nid=None,action=None):
    if nid:
        server_obj = get_object_or_404(Asset_Server,pk=nid)
        asset_obj = Asset.objects.filter(server_info=server_obj).first()
        if action == 'delete':
            server_obj.delete()
            return HttpResponseRedirect('/asset/list')
        if request.method == 'POST':
            server_form = ServerModeForm(request.POST, instance=server_obj)
            asset_form = AssetModeForm(request.POST,instance=asset_obj)
            if all([asset_form.is_valid(),server_form.is_valid()]):
                if action == 'edit':
                    server_form.save()
                    asset_form.save()
                    return HttpResponseRedirect('/asset/list')
        else:
            asset_form = AssetModeForm(instance=asset_obj)
            server_form = ServerModeForm(instance=server_obj)
        return render(request,'asset/asset-manage.html',{'asset_form':asset_form,'server_form':server_form,'action':action})

def asset_add(request):

    if request.method == "POST":
        form = AssetModeForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/asset/list')
    else:
        form = AssetModeForm()
    return render(request, 'asset/asset-add.html',{'form': form})

def server_add(request):

    if request.method == "POST":
        form = ServerModeForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/asset/add')
    else:
        form = ServerModeForm()
    return render(request, 'asset/server-add.html',{'form': form})

def test_chart(request):
    asset_count = Asset.objects.all().count()
    asset_type = Asset.objects.all()
    physics_count = Asset.objects.filter(asset_type='physics').count()
    server_count = Asset.objects.filter(asset_type='server').count()
    database_count = Asset.objects.filter(asset_type='database').count()
    nosql_count = Asset.objects.filter(asset_type='nosql').count()
    inside_count = Asset.objects.filter(asset_type='inside').count()

    return render(request,'asset/chart.html',{
        'asset_count':asset_count,'asset_type':asset_type,'physics_count':physics_count,
        'server_count':server_count,'database_count':database_count,'nosql_count':nosql_count,
        'inside_count':inside_count
    })

OpsPlatform/templates/asset/asset-add.html
{% extends 'base.html' %}

{% block css %}

{% endblock css %}

{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5><strong>资产中心</strong></h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">选项1</a>
                            </li>
                            <li><a href="#">选项2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <h5><strong>请确认是否已添加对应的服务器在进行操作</strong></h5>
                    <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">{% csrf_token %}
                            <div class="hr-line-dashed"></div>
                            {% for i in form %}
                            <div class="form-group">
                                <label class="col-sm-2 control-label">{{ i.label_tag }}</label>
                                <div class="col-sm-6">
                                    {{ i }}
                                    <div style="padding-top:10px;">
                                        {{ i.errors }}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3 ">
                                <button id="send" type="submit" class="btn btn-success" style="float: right">添加资产信息</button>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock content %}

OpsPlatform/templates/asset/asset-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

OpsPlatform/templates/asset/asset-list.html
{% extends 'base.html' %}

{% block css %}
<link href="/static/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
    <!-- Sweet Alert -->
    <link href="/static/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">
{% endblock css %}

{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5><strong>资产中心</strong></h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项1</a>
                                </li>
                                <li><a href="#">选项2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <table id="datatable" class="table table-striped table-bordered table-hover dataTables-example">
                            <thead>
                            <tr>
                                <th>资产编号</th>
                                <th>资产类型</th>
                                <th>放置区域</th>
                                <th>主机名</th>
                                <th>管理IP</th>
                                <th>配置</th>
                                <th>操作系统</th>
                                <th>状态</th>
                                <th>项目</th>
                                <th>操作</th>
                                <th>详细信息</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for ser in ass_list %}
                                    <tr class="gradeA">
                                    <td>{{ ser.name }}</td>
                                    <td>{{ ser.get_asset_type_display }}</td>
                                    <td>{{ ser.loaction.name }}</td>
                                    <td>{{ ser.server_info.hostname }}</td>
                                    <td>{{ ser.management_ip }}</td>
                                    <td>cpu:{{ ser.server_info.asset_server }}|mem:{{ ser.server_info.memory }}G|disk:{{ ser.server_info.disk }}G</td>

                                    <td>
                                        {% if ser.server_info.system_type == 'win' %}
                                            <i class="fa fa-windows"></i> {{ ser.server_info.get_system_type_display }}
                                        {% else %}
                                            <i class="fa fa-linux"></i> {{ ser.server_info.get_system_type_display}}
                                        {% endif %}
                                    </td>

                                    <td>
                                        {% if ser.status == 0 %}
                                            <span class="btn btn-success btn-sm">{{ ser.get_status_display }}</span>
                                        {% elif ser.status == 1 %}
                                            <span class="btn btn-danger btn-sm">{{ ser.get_status_display }}</span>
                                        {% else %}
                                            <span class="btn btn-warning btn-sm">{{ ser.get_status_display }}</span>
                                        {% endif %}
                                    </td>
                                    <td>{{ ser.project }}</td>
                                     <td class="center"><a href="{% url 'asset:asset_manage' nid=ser.server_info.pk action='edit'  %} "
                                                          class="btn btn-warning btn-sm" role="button"><i
                                            class="fa fa-pencil"></i></a>
                                        <button href="#" id="del" value="{{ ser.server_info.pk }}" class="btn btn-danger btn-sm demo4"><i
                                                class="fa fa-trash-o "></i></button>
                                    </td>
                                    <td><a href="{% url 'asset:asset_list' %}?nid={{ ser.server_info.pk }}"
                                               class="btn btn-xs btn-primary" data-toggle="tooltip"
                                               data-placement="bottom" title="" data-original-title="详情"> 详情{{ ser.server_info.pk }} </a></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>


                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <!-- Data Tables -->
    <script src="/static/js/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="/static/js/plugins/dataTables/dataTables.bootstrap.js"></script>

    <!-- Sweet alert -->
    <script src="/static/js/plugins/sweetalert/sweetalert.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#datatable').dataTable();

            $('.demo4').click(function () {
                id = $(this).attr("value");
                swal({
                        title: "您确定要删除这条记录",
                        text: "删除后将无法恢复，请谨慎操作！",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "是的，我要删除！",
                        cancelButtonText: "让我再考虑一下…",
                        closeOnConfirm: false,
                        closeOnCancel: false
                    },
                    function (isConfirm) {
                        if (isConfirm) {
                            base_url = /asset_manage/ + id + '/' + 'delete' ;
                            location.href = base_url;
                            location.href = "{% url 'asset:asset_list' %}";
                            swal("删除成功！", "您已经永久删除了这条信息。", "success");
                        } else {
                            swal("已取消", "您取消了删除操作！", "error");
                        }
                    });


            });
        });

    </script>


{% endblock js %}

OpsPlatform/templates/asset/asset-manage.html
{% extends 'base.html' %}

{% block css %}

{% endblock css %}

{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5><strong>资产中心</strong></h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">选项1</a>
                            </li>
                            <li><a href="#">选项2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">{% csrf_token %}
                        {% for ser in server_form %}
                            <div class="form-group">
                                <label class="col-sm-2 control-label">{{ ser.label_tag }}</label>
                                <div class="col-sm-6">
                                    {{ ser }}
                                    <div style="padding-top:10px;">
                                        {{ ser.errors }}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        <div class="hr-line-dashed"></div>
                        {% for i in asset_form %}
                            <div class="form-group">
                                <label class="col-sm-2 control-label">{{ i.label_tag }}</label>
                                <div class="col-sm-6">
                                    {{ i }}
                                    <div style="padding-top:10px;">
                                        {{ i.errors }}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-3 ">
                                <button id="send" type="submit" class="btn btn-success" style="float: right">更新</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock content %}

OpsPlatform/templates/asset/chart.html
{% extends 'base.html' %}

{% block css %}
    <link href="/static/css/custom.css" rel="stylesheet">
{% endblock css %}

{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5><strong>图表中心</strong></h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">选项1</a>
                            </li>
                            <li><a href="#">选项2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-warning">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-tasks  fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">{{ asset_count }}</div>
                                        <div>总资产</div>
                                    </div>
                                </div>
                            </div>
                            <a href="{% url 'asset:asset_list' %}">
                                <div class="panel-footer">
                                    <span class="pull-left">查看所有</span> <span class="pull-right"><i
                                        class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-database fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">10</div>
                                        <div>设备资产</div>
                                    </div>
                                </div>
                            </div>
                            <a href="#">
                                <div class="panel-footer">
                                    <span class="pull-left">查看所有</span> <span class="pull-right"><i
                                        class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-success">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-github-alt fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">0</div>
                                        <div>部署项目</div>
                                    </div>
                                </div>
                            </div>
                            <a href=#>
                                <div class="panel-footer">
                                    <span class="pull-left">查看所有</span> <span class="pull-right"><i
                                        class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-danger">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-clock-o fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">5</div>
                                        <div>计划任务</div>
                                    </div>
                                </div>
                            </div>
                            <a href="#">
                                <div class="panel-footer">
                                    <span class="pull-left">查看所有</span> <span class="pull-right"><i
                                        class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="hr-line-dashed"></div>

                <div class="row">
                    <div class="col-sm-6">
                    <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>柱状图</h5>

                    </div>
                    <div class="ibox-content">

                        <div class="echarts" id="main"></div>
                    </div>
                </div>

                </div>
            </div>

            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script src="/static/js/echarts.min.js"></script>

    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));

        // 指定图表的配置项和数据
        var option = {
            title: {
                text: '服务器分类'
            },
            tooltip: {},
            legend: {
                data: ['类型']
            },
            xAxis: {
                data: ["物理机", "云主机", "NOSQL", "云数据库", "内网服务器"]
                {#                data: [#}
                {#                    {% for type in asset_type %}#}
                {#                        '{{ type.get_asset_type_display }}',#}
                {#                    {% endfor %}#}
                {#                ]#}
            },
            yAxis: {},
            series: [{
                name: '台数',
                type: 'bar',
                {#                data: [5, 20, 36, 10, 10]#}
                data: [
                    {{ physics_count }},
                    {{ server_count }},
                    {{ database_count }},
                    {{ nosql_count }},
                    {{ inside_count }},
                ]
            }]
        };

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);

    </script>


{% endblock js %}